services:
  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - sqlite_data:/app/data # Mount a directory instead of a single file
    ports:
      - "8012:8012"

volumes:
  sqlite_data:
