[project]
name = "taralli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.6",
    "pydantic>=2.10.6",
]

[dependency-groups]
dev = [
    "djlint>=1.36.4",
    "ruff>=0.9.6",
]
