# Generated by Django 5.1.6 on 2025-02-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taralli", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="weight",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
