# Generated by Django 5.1.6 on 2025-02-15 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taralli", "0002_alter_meal_date_alter_weight_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="weight",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
